### ISSUE TITLE
example for User login

### ISSUE THREAD

**Issue by Terminator81** [whoot/Typo3Scan#26]
can you give me a example for the backend user login?

my password has ":;,-" and so on....

**Comment by whoot** [comment]
I don't quite understand what you are trying to accomplish.
You cant use Typo3Scan to login on the backend. If you have backend access you dont need Typo3Scan, because you can see all installed extensions and versions.

**Comment by Terminator81** [comment]
I have scaned my site the mesage appears that the exact Version cant be detected

So i thought i have to login

The same for extensions

**Comment by whoot** [comment]
If you have a login, then you don't need Typo3Scan because you can read all information in the backend.
Typo3Scan was developed for (blackbox) penetration tests. Version information is derived from specific files. In some cases it may not be possible to determine an exact version.
A login at the backend is not supported.
